[package]
name = "ametokei"
version = "0.2.0"
edition = "2024"

authors = ["Maachue <maachue.project@outlook.com>"]
description = """
Another tty-clock with customizable & weather effect.
"""
readme = "README.md"
repository = "https://github.com/maachue/ametokei"
keywords = ["cli", "time", "terminal"]
categories = ["date-and-time", "command-line-interface"]
homepage = "https://github.com/maachue/ametokei"
license = "MIT"

[dependencies]
# CLI
clap = { version = "4.5.60", features = ["derive"] }

# TUI core
crossterm = { version = "0.29.0", features = ["event-stream"] }
ratatui = { version = "0.30.0", features = ["serde"] }
itertools = "0.14.0"
tinyvec = "1.10.0"
rand = "0.10.0"

# time
chrono = "0.4.43"

# truely width for UTF-8
unicode-width = "0.2.2"

# async
futures = "0.3.32"
tokio = { version = "1.49.0", features = ["full"] }

# config
serde = { version = "1.0.228", features = ["derive"] }
toml = "1.0.3"
directories = "6.0.0"

# pertty error handler
color-eyre = "0.6.5"

# log (for debug)
tracing = { version = "0.1.44", optional = true }
tracing-appender = { version = "0.2.4", optional = true }
tracing-subscriber = { version = "0.3.22", optional = true }
thiserror = "2.0.18"

[features]
default = []

# debug only
tracing = ["dep:tracing", "dep:tracing-appender", "dep:tracing-subscriber"]

# ESC[?2026h/l
# Make it as a feature because ratatui has the double buffer.
synchronized_updates = []

[profile.release]
codegen-units = 3
lto = true
opt-level = 3
strip = true
panic = "abort"
